version: "3"
services:
  queue:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: queue
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: order-worker
      MYSQL_DATABASE: order
      MYSQL_USER: order-worker
      MYSQL_PASSWORD: order-worker
    ports:
      - "3306:3306"
    container_name: db
  api:
    image: gabrielborc/order-api
    restart: on-failure
    environment:
      NODE_ENV: production
      DB_CLIENT: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: order-worker
      DB_PASSWORD: order-worker
      DB_DATABASE: order
      HOST_QUEUE: queue
    ports:
      - "3333:3333"
    depends_on:
      - db
      - queue
    links:
      - db
      - queue
  worker:
    image: gabrielborc/order-worker
    restart: on-failure
    environment:
      SPRING_DATASOURCE_HOST: db
      SPRING_RABBITMQ_HOST: queue
    ports:
      - "8080:8080"
    depends_on:
      - db
      - queue
    links:
      - db
      - queue
